from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any


def loc(en: str, de: str) -> dict[str, str]:
    return {"en": en, "de": de}


NOW = datetime.now(timezone.utc)

PATIENTS = [
    {
        "id": "patient-ahmad-001",
        "name": "Ahmad Mansour",
        "age": 74,
        "diagnosis": loc("Alzheimer's Disease", "Alzheimer-Krankheit"),
        "stage": loc("Moderate", "Mittel"),
        "location": loc("Home", "Zuhause"),
        "status": loc("Stable", "Stabil"),
        "cognitiveScore": 72,
        "mood": loc("Calm", "Ruhig"),
        "currentState": loc("Stable", "Stabil"),
        "primaryCaregiverId": "caregiver-sarah-001",
        "assignedDoctorId": "doctor-lena-001",
        "languagePreference": "en",
        "avatar": "https://images.unsplash.com/photo-1519241047957-be31d7379a5d?auto=format&fit=crop&w=400&q=80",
        "diagnosisDate": "2023-09-14",
        "residence": loc("Munich, Germany", "München, Deutschland"),
        "aiConfidence": 84,
        "riskScores": {
            "wandering": 58,
            "fall": 26,
            "confusion": 34,
            "medication": 19,
            "dehydration": 27,
            "isolation": 48,
        },
        "domainScores": {
            "moodStability": 78,
            "memoryRecall": 51,
            "orientation": 64,
            "safety": 82,
            "socialResponse": 69,
        },
        "sleepQuality": 68,
        "medicationAdherence": 91,
        "socialTrend": loc("Improved", "Verbessert"),
        "lastInteraction": "8 minutes ago",
        "emergencyContacts": ["caregiver-sarah-001", "caregiver-omar-001"],
    },
    {
        "id": "patient-nora-002",
        "name": "Nora Becker",
        "age": 79,
        "diagnosis": loc("Mild Cognitive Impairment", "Leichte kognitive Beeinträchtigung"),
        "stage": loc("Early", "Früh"),
        "location": loc("Assisted Living", "Betreutes Wohnen"),
        "status": loc("Observed", "Beobachtet"),
        "cognitiveScore": 81,
        "mood": loc("Steady", "Ausgeglichen"),
        "currentState": loc("Under observation", "Unter Beobachtung"),
        "primaryCaregiverId": "caregiver-julia-002",
        "assignedDoctorId": "doctor-lena-001",
        "languagePreference": "de",
        "avatar": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
        "diagnosisDate": "2024-01-18",
        "residence": loc("Berlin, Germany", "Berlin, Deutschland"),
        "aiConfidence": 79,
        "riskScores": {
            "wandering": 24,
            "fall": 34,
            "confusion": 21,
            "medication": 16,
            "dehydration": 18,
            "isolation": 39,
        },
        "domainScores": {
            "moodStability": 82,
            "memoryRecall": 73,
            "orientation": 88,
            "safety": 77,
            "socialResponse": 74,
        },
        "sleepQuality": 74,
        "medicationAdherence": 94,
        "socialTrend": loc("Stable", "Stabil"),
        "lastInteraction": "12 minutes ago",
        "emergencyContacts": ["caregiver-julia-002"],
    },
]

CAREGIVERS = [
    {
        "id": "caregiver-sarah-001",
        "name": "Sarah Mansour",
        "relationship": loc("Daughter", "Tochter"),
        "accessLevel": "primary",
        "patientIds": ["patient-ahmad-001"],
        "permissions": ["reports", "location", "voice", "medical_reports"],
        "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
        "voiceSampleStatus": loc("Available", "Verfügbar"),
        "lastInteraction": loc("Today at 10:12", "Heute um 10:12"),
        "emotionalImpact": loc("High calming effect", "Hohe beruhigende Wirkung"),
        "aiNote": loc("Sarah’s voice reduced anxiety in 82% of recent confusion episodes.", "Sarahs Stimme reduzierte Angst in 82 % der jüngsten Verwirrungsepisoden."),
    },
    {
        "id": "caregiver-omar-001",
        "name": "Omar Mansour",
        "relationship": loc("Son", "Sohn"),
        "accessLevel": "support",
        "patientIds": ["patient-ahmad-001"],
        "permissions": ["reports", "family_updates"],
        "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
        "voiceSampleStatus": loc("Available", "Verfügbar"),
        "lastInteraction": loc("Yesterday", "Gestern"),
        "emotionalImpact": loc("Moderate calming effect", "Mittlere beruhigende Wirkung"),
        "aiNote": loc("Omar is most effective during afternoon reassurance check-ins.", "Omar wirkt am besten bei beruhigenden Nachmittagsanrufen."),
    },
    {
        "id": "caregiver-julia-002",
        "name": "Julia Becker",
        "relationship": loc("Niece", "Nichte"),
        "accessLevel": "primary",
        "patientIds": ["patient-nora-002"],
        "permissions": ["reports", "location"],
        "photo": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80",
        "voiceSampleStatus": loc("Pending", "Ausstehend"),
        "lastInteraction": loc("Today", "Heute"),
        "emotionalImpact": loc("Supportive", "Unterstützend"),
        "aiNote": loc("Short weekly check-ins maintain positive orientation.", "Kurze wöchentliche Gespräche stabilisieren die Orientierung."),
    },
]

DOCTORS = [
    {
        "id": "doctor-lena-001",
        "name": "Dr. Lena Fischer",
        "specialty": loc("Neurology", "Neurologie"),
        "assignedPatients": ["patient-ahmad-001", "patient-nora-002"],
        "clinicName": "Future Memory Clinic",
        "photo": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80",
    }
]

PEOPLE = [
    {
        "id": "person-sarah-001",
        "patientId": "patient-ahmad-001",
        "name": "Sarah Mansour",
        "relationship": loc("Daughter", "Tochter"),
        "calmingEffect": loc("High", "Hoch"),
        "lastInteraction": loc("Visited yesterday", "Gestern besucht"),
        "voiceSampleStatus": loc("Available", "Verfügbar"),
        "emotionalImpact": loc("Strong reassurance response", "Starke beruhigende Wirkung"),
        "notes": loc("Most effective calming voice cue.", "Wirksamster beruhigender Stimmhinweis."),
        "photo": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    },
    {
        "id": "person-omar-001",
        "patientId": "patient-ahmad-001",
        "name": "Omar Mansour",
        "relationship": loc("Son", "Sohn"),
        "calmingEffect": loc("Medium", "Mittel"),
        "lastInteraction": loc("Yesterday by phone", "Gestern telefonisch"),
        "voiceSampleStatus": loc("Available", "Verfügbar"),
        "emotionalImpact": loc("Positive recognition", "Positive Wiedererkennung"),
        "notes": loc("Good during afternoon check-ins.", "Hilfreich bei Nachmittagsanrufen."),
        "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    },
    {
        "id": "person-layla-001",
        "patientId": "patient-ahmad-001",
        "name": "Layla Mansour",
        "relationship": loc("Wife", "Ehefrau"),
        "calmingEffect": loc("High", "Hoch"),
        "lastInteraction": loc("Morning conversation", "Gespräch am Morgen"),
        "voiceSampleStatus": loc("Favorite voice cue", "Bevorzugte Stimme"),
        "emotionalImpact": loc("Warm positive memory trigger", "Warmes positives Erinnerungssignal"),
        "notes": loc("Familiar routines with Layla reduce evening anxiety.", "Vertraute Rituale mit Layla reduzieren Abendangst."),
        "photo": "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=300&q=80",
    },
    {
        "id": "person-mother-001",
        "patientId": "patient-ahmad-001",
        "name": "Fatima Mansour",
        "relationship": loc("Mother", "Mutter"),
        "calmingEffect": loc("Deep emotional memory", "Tiefe emotionale Erinnerung"),
        "lastInteraction": loc("Historical memory", "Historische Erinnerung"),
        "voiceSampleStatus": loc("Unavailable", "Nicht verfügbar"),
        "emotionalImpact": loc("Strong nostalgia trigger", "Starker Nostalgieauslöser"),
        "notes": loc("Use validation and redirection when Ahmad speaks about his mother.", "Bei Gesprächen über die Mutter Validierung und sanfte Umleitung verwenden."),
        "photo": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80",
    },
    {
        "id": "person-doctor-001",
        "patientId": "patient-ahmad-001",
        "name": "Dr. Lena Fischer",
        "relationship": loc("Doctor", "Ärztin"),
        "calmingEffect": loc("Clinical trust", "Klinisches Vertrauen"),
        "lastInteraction": loc("Last review Monday", "Letzte Untersuchung am Montag"),
        "voiceSampleStatus": loc("Not applicable", "Nicht zutreffend"),
        "emotionalImpact": loc("Reassuring when paired with family context", "Beruhigend in Kombination mit familiärem Kontext"),
        "notes": loc("Review evening confusion trend at next follow-up.", "Abendliche Verwirrung beim nächsten Termin prüfen."),
        "photo": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80",
    },
]

MEMORIES = [
    {
        "id": "memory-wedding-001",
        "patientId": "patient-ahmad-001",
        "title": loc("Wedding Photo", "Hochzeitsfoto"),
        "type": "photo",
        "people": ["Layla Mansour", "Ahmad Mansour"],
        "emotionalImpact": loc("Strong positive emotional response", "Starke positive emotionale Reaktion"),
        "date": "1974-06-21",
        "tags": ["family", "wedding", "joy"],
        "consentStatus": "granted",
        "usageCount": 14,
        "aiSummary": loc("Used 14 times this month and frequently reduces anxiety.", "Wurde diesen Monat 14 Mal verwendet und reduziert häufig Angst."),
        "mediaUrl": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
        "memorySourceLabel": loc("Family-provided original", "Von der Familie bereitgestelltes Original"),
    },
    {
        "id": "memory-home-001",
        "patientId": "patient-ahmad-001",
        "title": loc("Old Family Home", "Altes Familienhaus"),
        "type": "photo",
        "people": ["Fatima Mansour"],
        "emotionalImpact": loc("Deep grounding memory", "Tief verankernde Erinnerung"),
        "date": "1961-04-12",
        "tags": ["home", "childhood", "mother"],
        "consentStatus": "granted",
        "usageCount": 9,
        "aiSummary": loc("Strong orientation trigger when paired with Sarah’s voice.", "Starkes Orientierungssignal in Kombination mit Sarahs Stimme."),
        "mediaUrl": "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=800&q=80",
        "memorySourceLabel": loc("Family-provided original", "Von der Familie bereitgestelltes Original"),
    },
    {
        "id": "memory-voice-001",
        "patientId": "patient-ahmad-001",
        "title": loc("Sarah Voice Memory", "Sarahs Stimmerinnerung"),
        "type": "audio",
        "people": ["Sarah Mansour"],
        "emotionalImpact": loc("Most effective calming memory", "Wirksamste beruhigende Erinnerung"),
        "date": "2025-02-01",
        "tags": ["voice", "family", "comfort"],
        "consentStatus": "granted",
        "usageCount": 26,
        "aiSummary": loc("Reduces confusion episode duration by an estimated 38%.", "Reduziert die Dauer von Verwirrungsepisoden schätzungsweise um 38 %."),
        "mediaUrl": "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80",
        "memorySourceLabel": loc("Family-provided voice sample", "Von der Familie bereitgestellte Sprachprobe"),
    },
    {
        "id": "memory-music-001",
        "patientId": "patient-ahmad-001",
        "title": loc("Old Music Playlist", "Alte Musikplaylist"),
        "type": "audio",
        "people": ["Layla Mansour"],
        "emotionalImpact": loc("Moderate calming effect", "Mäßige beruhigende Wirkung"),
        "date": "2025-01-14",
        "tags": ["music", "comfort", "evening"],
        "consentStatus": "granted",
        "usageCount": 18,
        "aiSummary": loc("Most effective before sunset during transition periods.", "Am wirksamsten vor Sonnenuntergang in Übergangsphasen."),
        "mediaUrl": "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=800&q=80",
        "memorySourceLabel": loc("Family-curated media", "Von der Familie kuratierte Medien"),
    },
]

EVENTS = [
    {
        "id": "event-0810",
        "patientId": "patient-ahmad-001",
        "type": "safety",
        "timestamp": (NOW - timedelta(hours=13, minutes=20)).isoformat(),
        "title": loc("Woke up", "Aufgewacht"),
        "description": loc("Morning orientation prompt delivered successfully.", "Morgendliche Orientierung erfolgreich durchgeführt."),
        "severity": "low",
        "aiInterpretation": loc("Stable wake routine supports orientation.", "Stabile Morgenroutine unterstützt die Orientierung."),
        "actionTaken": loc("Bedroom light and clock cue activated.", "Schlafzimmerlicht und Uhrhinweis aktiviert."),
    },
    {
        "id": "event-0830",
        "patientId": "patient-ahmad-001",
        "type": "medication",
        "timestamp": (NOW - timedelta(hours=13)).isoformat(),
        "title": loc("Breakfast", "Frühstück"),
        "description": loc("Breakfast completed with hydration reminder.", "Frühstück mit Trinkhinweis abgeschlossen."),
        "severity": "low",
        "aiInterpretation": loc("Nutrition and hydration were stable.", "Ernährung und Flüssigkeitszufuhr waren stabil."),
        "actionTaken": loc("Logged to daily care record.", "Im täglichen Pflegeprotokoll erfasst."),
    },
    {
        "id": "event-0900",
        "patientId": "patient-ahmad-001",
        "type": "medication",
        "timestamp": (NOW - timedelta(hours=12, minutes=30)).isoformat(),
        "title": loc("Medicine taken", "Medikament eingenommen"),
        "description": loc("Morning medication taken next to water glass.", "Morgenmedikament neben dem Wasserglas eingenommen."),
        "severity": "low",
        "aiInterpretation": loc("Medication adherence remains high.", "Die Medikamenteneinnahme bleibt hoch."),
        "actionTaken": loc("Dose marked complete by caregiver.", "Dosis von der Betreuungsperson als erledigt markiert."),
    },
    {
        "id": "event-1012",
        "patientId": "patient-ahmad-001",
        "type": "family",
        "timestamp": (NOW - timedelta(hours=11, minutes=18)).isoformat(),
        "title": loc("Talked with daughter Sarah", "Mit Tochter Sarah gesprochen"),
        "description": loc("Short reassurance call lowered stress markers.", "Kurzer beruhigender Anruf senkte Stressmarker."),
        "severity": "low",
        "aiInterpretation": loc("Family voice produced immediate calming effect.", "Familienstimme zeigte sofortige beruhigende Wirkung."),
        "actionTaken": loc("Voice sample reinforced in AI playbook.", "Sprachprobe im KI-Playbook verstärkt."),
    },
    {
        "id": "event-1105",
        "patientId": "patient-ahmad-001",
        "type": "memory",
        "timestamp": (NOW - timedelta(hours=10, minutes=25)).isoformat(),
        "title": loc("Asked “Where am I?” twice", "Zweimal gefragt: „Wo bin ich?“"),
        "description": loc("Repeated orientation question detected during transition from lounge to kitchen.", "Wiederholte Orientierungsfrage beim Wechsel vom Wohnzimmer in die Küche erkannt."),
        "severity": "medium",
        "aiInterpretation": loc("Mild confusion episode with no immediate safety escalation.", "Leichte Verwirrungsepisode ohne unmittelbare Sicherheitseskalation."),
        "actionTaken": loc("Calm voice + location reminder played.", "Beruhigende Stimme und Orts-Erinnerung abgespielt."),
    },
    {
        "id": "event-1320",
        "patientId": "patient-ahmad-001",
        "type": "mood",
        "timestamp": (NOW - timedelta(hours=8, minutes=10)).isoformat(),
        "title": loc("Mild anxiety detected", "Leichte Angst erkannt"),
        "description": loc("Elevated pacing and shorter responses observed after neighborhood noise.", "Erhöhtes Umhergehen und kürzere Antworten nach Lärm in der Nachbarschaft beobachtet."),
        "severity": "medium",
        "aiInterpretation": loc("Noise appears to be an evening-adjacent agitation trigger.", "Lärm scheint ein Auslöser für Unruhe in Übergangszeiten zu sein."),
        "actionTaken": loc("Noise reduced and family photo shown.", "Lärm reduziert und Familienfoto gezeigt."),
    },
    {
        "id": "event-1400",
        "patientId": "patient-ahmad-001",
        "type": "memory",
        "timestamp": (NOW - timedelta(hours=7, minutes=30)).isoformat(),
        "title": loc("Watched family video", "Familienvideo angesehen"),
        "description": loc("Played wedding and home video sequence.", "Hochzeits- und Hausvideo-Sequenz abgespielt."),
        "severity": "low",
        "aiInterpretation": loc("Positive emotional response with improved eye contact.", "Positive emotionale Reaktion mit verbessertem Blickkontakt."),
        "actionTaken": loc("Saved as effective calming intervention.", "Als wirksame beruhigende Intervention gespeichert."),
    },
    {
        "id": "event-1545",
        "patientId": "patient-ahmad-001",
        "type": "ai_intervention",
        "timestamp": (NOW - timedelta(hours=5, minutes=45)).isoformat(),
        "title": loc("Stable state restored", "Stabiler Zustand wiederhergestellt"),
        "description": loc("Patient returned to calm baseline after guided redirection.", "Patient kehrte nach sanfter Umleitung zum ruhigen Ausgangszustand zurück."),
        "severity": "low",
        "aiInterpretation": loc("Gentle redirection outperformed direct correction.", "Sanfte Umleitung war wirksamer als direkte Korrektur."),
        "actionTaken": loc("Marked as preferred de-escalation sequence.", "Als bevorzugte Deeskalationssequenz markiert."),
    },
]

EPISODES = [
    {
        "id": "episode-1912",
        "patientId": "patient-ahmad-001",
        "type": loc("Confusion episode", "Verwirrungsepisode"),
        "trigger": loc("Noise + fatigue", "Lärm + Müdigkeit"),
        "duration": "4 min",
        "patientPhrase": loc("I want to go home", "Ich will nach Hause"),
        "aiResponse": loc("You are safe here, Ahmad. Tell me what you loved most about your home.", "Sie sind hier sicher, Ahmad. Erzählen Sie mir, was Sie an Ihrem Zuhause am meisten geliebt haben."),
        "interventionUsed": loc("Calm voice + location reminder", "Beruhigende Stimme + Orts-Erinnerung"),
        "outcome": loc("Calmed after 4 minutes", "Nach 4 Minuten beruhigt"),
        "severity": "medium",
        "doctorReviewRequired": False,
        "timestamp": (NOW - timedelta(days=1, hours=2)).isoformat(),
    },
    {
        "id": "episode-1824",
        "patientId": "patient-ahmad-001",
        "type": loc("Evening anxiety", "Abendliche Angst"),
        "trigger": loc("Sunset transition", "Übergang bei Sonnenuntergang"),
        "duration": "7 min",
        "patientPhrase": loc("Where is my mother?", "Wo ist meine Mutter?"),
        "aiResponse": loc("Tell me about your mother. What did you love most about her?", "Erzählen Sie mir von Ihrer Mutter. Was haben Sie an ihr am meisten geliebt?"),
        "interventionUsed": loc("Family photo + Sarah voice playback", "Familienfoto + Sarahs Stimme"),
        "outcome": loc("Anxiety reduced with photo recall", "Angst mit Foto-Erinnerung reduziert"),
        "severity": "high",
        "doctorReviewRequired": True,
        "timestamp": (NOW - timedelta(days=2, hours=4)).isoformat(),
    },
    {
        "id": "episode-0630",
        "patientId": "patient-ahmad-001",
        "type": loc("Unsafe exit attempt", "Unsicherer Ausgangsversuch"),
        "trigger": loc("Door open after dinner", "Türöffnung nach dem Abendessen"),
        "duration": "2 min",
        "patientPhrase": loc("I need to go to work", "Ich muss zur Arbeit"),
        "aiResponse": loc("You have done enough for today. Let us sit for a moment together.", "Sie haben heute schon genug getan. Lassen Sie uns kurz zusammen sitzen."),
        "interventionUsed": loc("Door alert + caregiver step-by-step guidance", "Türalarm + schrittweise Anleitung durch Betreuungsperson"),
        "outcome": loc("Returned safely to living room", "Sicher ins Wohnzimmer zurückgeführt"),
        "severity": "high",
        "doctorReviewRequired": True,
        "timestamp": (NOW - timedelta(days=4, hours=1)).isoformat(),
    },
]

MEDICATIONS = [
    {
        "id": "med-donepezil-001",
        "patientId": "patient-ahmad-001",
        "name": "Donepezil",
        "dosage": "10 mg",
        "schedule": loc("09:00 daily", "09:00 täglich"),
        "adherenceStatus": loc("Taken", "Eingenommen"),
        "lastTaken": (NOW - timedelta(hours=12, minutes=30)).isoformat(),
        "missedCount": 1,
    },
    {
        "id": "med-vitd-001",
        "patientId": "patient-ahmad-001",
        "name": "Vitamin D",
        "dosage": "1000 IU",
        "schedule": loc("18:00 daily", "18:00 täglich"),
        "adherenceStatus": loc("Scheduled", "Geplant"),
        "lastTaken": (NOW - timedelta(days=1, hours=4)).isoformat(),
        "missedCount": 0,
    },
    {
        "id": "med-water-001",
        "patientId": "patient-ahmad-001",
        "name": "Hydration reminder",
        "dosage": "250 ml",
        "schedule": loc("Every 3 hours", "Alle 3 Stunden"),
        "adherenceStatus": loc("On track", "Im Plan"),
        "lastTaken": (NOW - timedelta(hours=2)).isoformat(),
        "missedCount": 0,
    },
]

RISK_SCORES = [
    {
        "id": "risk-1",
        "patientId": "patient-ahmad-001",
        "wandering": 46,
        "fall": 24,
        "confusion": 28,
        "medication": 18,
        "dehydration": 25,
        "isolation": 44,
        "timestamp": (NOW - timedelta(days=6)).isoformat(),
    },
    {
        "id": "risk-2",
        "patientId": "patient-ahmad-001",
        "wandering": 49,
        "fall": 24,
        "confusion": 31,
        "medication": 17,
        "dehydration": 24,
        "isolation": 43,
        "timestamp": (NOW - timedelta(days=5)).isoformat(),
    },
    {
        "id": "risk-3",
        "patientId": "patient-ahmad-001",
        "wandering": 51,
        "fall": 25,
        "confusion": 29,
        "medication": 18,
        "dehydration": 28,
        "isolation": 42,
        "timestamp": (NOW - timedelta(days=4)).isoformat(),
    },
    {
        "id": "risk-4",
        "patientId": "patient-ahmad-001",
        "wandering": 55,
        "fall": 25,
        "confusion": 35,
        "medication": 19,
        "dehydration": 26,
        "isolation": 45,
        "timestamp": (NOW - timedelta(days=3)).isoformat(),
    },
    {
        "id": "risk-5",
        "patientId": "patient-ahmad-001",
        "wandering": 54,
        "fall": 26,
        "confusion": 36,
        "medication": 19,
        "dehydration": 28,
        "isolation": 46,
        "timestamp": (NOW - timedelta(days=2)).isoformat(),
    },
    {
        "id": "risk-6",
        "patientId": "patient-ahmad-001",
        "wandering": 56,
        "fall": 26,
        "confusion": 33,
        "medication": 20,
        "dehydration": 27,
        "isolation": 47,
        "timestamp": (NOW - timedelta(days=1)).isoformat(),
    },
    {
        "id": "risk-7",
        "patientId": "patient-ahmad-001",
        "wandering": 58,
        "fall": 26,
        "confusion": 34,
        "medication": 19,
        "dehydration": 27,
        "isolation": 48,
        "timestamp": NOW.isoformat(),
    },
]

CONSENTS = [
    {
        "id": "consent-audio-001",
        "patientId": "patient-ahmad-001",
        "category": loc("Audio data", "Audiodaten"),
        "grantedTo": loc("Family care team", "Familienpflegeteam"),
        "status": "granted",
        "timestamp": (NOW - timedelta(days=40)).isoformat(),
        "expiresAt": (NOW + timedelta(days=180)).isoformat(),
    },
    {
        "id": "consent-location-001",
        "patientId": "patient-ahmad-001",
        "category": loc("Location sharing", "Standortfreigabe"),
        "grantedTo": loc("Primary caregiver", "Hauptbetreuungsperson"),
        "status": "granted",
        "timestamp": (NOW - timedelta(days=40)).isoformat(),
        "expiresAt": (NOW + timedelta(days=180)).isoformat(),
    },
    {
        "id": "consent-memory-001",
        "patientId": "patient-ahmad-001",
        "category": loc("Memory reconstruction", "Gedächtnisrekonstruktion"),
        "grantedTo": loc("Doctor review only", "Nur ärztliche Prüfung"),
        "status": "pending",
        "timestamp": (NOW - timedelta(days=5)).isoformat(),
        "expiresAt": (NOW + timedelta(days=60)).isoformat(),
    },
    {
        "id": "consent-voice-001",
        "patientId": "patient-ahmad-001",
        "category": loc("Voice samples", "Sprachproben"),
        "grantedTo": loc("Family support AI", "Familienunterstützende KI"),
        "status": "requires_review",
        "timestamp": (NOW - timedelta(days=3)).isoformat(),
        "expiresAt": (NOW + timedelta(days=30)).isoformat(),
    },
]

REPORTS = [
    {
        "id": "report-daily-001",
        "patientId": "patient-ahmad-001",
        "period": "daily",
        "title": loc("Daily AI Summary", "Tägliche KI-Zusammenfassung"),
        "summary": loc("Ahmad had a stable morning, took medication on time, and responded well to Sarah’s voice after mild confusion.", "Ahmad hatte einen stabilen Morgen, nahm seine Medikamente pünktlich ein und reagierte nach leichter Verwirrung gut auf Sarahs Stimme."),
        "observations": [
            loc("Confusion rose briefly around 11:05.", "Die Verwirrung stieg kurz gegen 11:05 Uhr an."),
            loc("Family video improved emotional regulation.", "Das Familienvideo verbesserte die emotionale Regulation."),
        ],
        "recommendations": [
            loc("Reduce noise between 18:00 and 20:00.", "Lärm zwischen 18:00 und 20:00 reduzieren."),
            loc("Use Sarah’s voice before sunset transitions.", "Sarahs Stimme vor Übergängen bei Sonnenuntergang verwenden."),
        ],
        "generatedBy": "seed-ai",
        "reviewedByDoctor": False,
        "createdAt": (NOW - timedelta(hours=2)).isoformat(),
        "provider": "seeded",
        "model": "memind-demo",
        "output": {"cached": True},
    },
    {
        "id": "report-weekly-001",
        "patientId": "patient-ahmad-001",
        "period": "weekly",
        "title": loc("Weekly Family Report", "Wöchentlicher Familienbericht"),
        "summary": loc("Cognitive stability remained moderate with evening confusion as the main pressure point. Family voice remains the strongest calming intervention.", "Die kognitive Stabilität blieb moderat, wobei abendliche Verwirrung der wichtigste Belastungspunkt war. Die Familienstimme bleibt die stärkste beruhigende Intervention."),
        "observations": [
            loc("Orientation questions increased by 18% compared to the previous week.", "Orientierungsfragen stiegen im Vergleich zur Vorwoche um 18 % an."),
            loc("Medication adherence remained high at 91%.", "Die Medikamenteneinnahme blieb mit 91 % hoch."),
        ],
        "recommendations": [
            loc("Review evening routine and environmental noise.", "Abendroutine und Umgebungsgeräusche überprüfen."),
            loc("Schedule more family calls in the afternoon.", "Mehr Familienanrufe am Nachmittag einplanen."),
        ],
        "generatedBy": "seed-ai",
        "reviewedByDoctor": True,
        "createdAt": (NOW - timedelta(days=1)).isoformat(),
        "provider": "seeded",
        "model": "memind-demo",
        "output": {"cached": True},
    },
]

AI_OBSERVATIONS = [
    {
        "id": "obs-001",
        "patientId": "patient-ahmad-001",
        "type": "clinical_observations",
        "confidence": 84,
        "summary": loc("Repeated orientation questions increased over the last 7 days.", "Wiederholte Orientierungsfragen nahmen in den letzten 7 Tagen zu."),
        "recommendation": loc("Review environmental triggers and maintain non-confrontational orientation cues.", "Umgebungsauslöser prüfen und nicht konfrontative Orientierungshinweise beibehalten."),
        "doctorReviewRequired": True,
        "createdAt": (NOW - timedelta(hours=6)).isoformat(),
        "provider": "seeded",
        "model": "memind-demo",
        "output": {
            "observation_summary": loc("Mild increase in evening confusion with stable safety markers.", "Leichter Anstieg der abendlichen Verwirrung bei stabilen Sicherheitsmarkern."),
            "trend_note": loc("Observation only; not a diagnosis.", "Nur Beobachtung; keine Diagnose."),
        },
    }
]

DOCTOR_NOTES = [
    {
        "id": "doctor-note-001",
        "patientId": "patient-ahmad-001",
        "doctorId": "doctor-lena-001",
        "note": loc("Recommend avoiding direct correction when Ahmad asks about his mother.", "Empfehlung: direkte Korrektur vermeiden, wenn Ahmad nach seiner Mutter fragt."),
        "carePlan": loc("Use validation, family voice, and visual memory cues before sunset.", "Vor Sonnenuntergang Validierung, Familienstimmen und visuelle Erinnerungshinweise verwenden."),
        "followUpRecommendation": loc("Review trend data in 2 weeks.", "Trenddaten in 2 Wochen erneut prüfen."),
        "createdAt": (NOW - timedelta(days=2)).isoformat(),
    }
]

AUDIT_LOGS = [
    {
        "id": "audit-001",
        "actorRole": "doctor",
        "action": "viewed_clinical_console",
        "patientId": "patient-ahmad-001",
        "target": "clinical_console",
        "details": {"view": "cognitive_trend_analysis"},
        "consentStatus": "granted",
        "timestamp": (NOW - timedelta(hours=3)).isoformat(),
    },
    {
        "id": "audit-002",
        "actorRole": "caregiver",
        "action": "viewed_report",
        "patientId": "patient-ahmad-001",
        "target": "weekly_report",
        "details": {"reportId": "report-weekly-001"},
        "consentStatus": "granted",
        "timestamp": (NOW - timedelta(hours=2, minutes=30)).isoformat(),
    },
    {
        "id": "audit-003",
        "actorRole": "admin",
        "action": "reviewed_consent",
        "patientId": "patient-ahmad-001",
        "target": "consent-memory-001",
        "details": {"status": "pending"},
        "consentStatus": "pending",
        "timestamp": (NOW - timedelta(hours=1, minutes=45)).isoformat(),
    },
]

DEVICES = [
    {"id": "device-watch-001", "patientId": "patient-ahmad-001", "name": "Memind Home Beacon", "status": "online", "lastSeen": (NOW - timedelta(minutes=2)).isoformat()},
    {"id": "device-door-001", "patientId": "patient-ahmad-001", "name": "Door Sensor", "status": "online", "lastSeen": (NOW - timedelta(minutes=5)).isoformat()},
]

ALERTS = [
    {"id": "alert-001", "patientId": "patient-ahmad-001", "level": "medium", "title": loc("Wandering risk elevated this week", "Weglaufrisiko diese Woche erhöht"), "createdAt": (NOW - timedelta(hours=5)).isoformat()},
    {"id": "alert-002", "patientId": "patient-ahmad-001", "level": "low", "title": loc("Hydration reminder overdue by 20 minutes", "Trink-Erinnerung um 20 Minuten verzögert"), "createdAt": (NOW - timedelta(minutes=20)).isoformat()},
]

SYSTEM_HEALTH = [
    {"id": "system-health-001", "service": "api", "status": "healthy", "value": "99.98% uptime", "timestamp": NOW.isoformat()},
    {"id": "system-health-002", "service": "ai_runtime", "status": "healthy", "value": "OpenAI via provider abstraction", "timestamp": NOW.isoformat()},
    {"id": "system-health-003", "service": "storage", "status": "healthy", "value": "Mongo connected", "timestamp": NOW.isoformat()},
]

COLLECTION_SEEDS: dict[str, list[dict[str, Any]]] = {
    "patients": PATIENTS,
    "caregivers": CAREGIVERS,
    "doctors": DOCTORS,
    "people": PEOPLE,
    "memories": MEMORIES,
    "events": EVENTS,
    "episodes": EPISODES,
    "medications": MEDICATIONS,
    "risk_scores": RISK_SCORES,
    "consents": CONSENTS,
    "reports": REPORTS,
    "ai_observations": AI_OBSERVATIONS,
    "doctor_notes": DOCTOR_NOTES,
    "audit_logs": AUDIT_LOGS,
    "devices": DEVICES,
    "alerts": ALERTS,
    "system_health": SYSTEM_HEALTH,
}


async def seed_demo_data(db) -> None:
    for collection_name, docs in COLLECTION_SEEDS.items():
        collection = db[collection_name]
        for doc in docs:
            await collection.update_one({"id": doc["id"]}, {"$setOnInsert": doc}, upsert=True)
